feat: merged mainline.
Co-authored-by: JackAltman
<82563979+JackA1ltman@users.noreply.github.com>

diff --git a/.github/workflows/patch-no-kprobe/action.yml b/.github/workflows/patch-no-kprobe/action.yml
--- a/.github/workflows/patch-no-kprobe/action.yml
+++ b/.github/workflows/patch-no-kprobe/action.yml
@@ -50,6 +50,51 @@ runs:
           if grep -q "can_umount" "fs/namespace.c" && grep -q "ksu_init" "fs/exec.c"; then
             echo "Your kernel source code appears to have been manually patched, so this step is skipped."
 
+          # Detect SuSFS is used to enable the SuSFS inline hook
+          elif [[ ${{ env.SUSFS_ENABLE }} == "true" ]] && [[ ${{ env.SUSFS_UPDATE }} == "true" ]]; then
+            cp /tmp/Patches/susfs_inline_hook_patches.sh ./
+            bash susfs_inline_hook_patches.sh ./
+
+            echo "executed SuSFS inline hook successfully."
+
+            if [[ ${{ env.FIRST_VERSION }} -le 4 ]] && [[ ${{ env.SECOND_VERSION }} -le 9 ]]; then
+                cp /tmp/Patches/backport_patches.sh ./
+
+                bash backport_patches.sh
+                if grep -q "kernel_read" "fs/read_write.c"; then
+                    echo ">>>>>>>>>>>>>>>Backport Patch<<<<<<<<<<<<<<<<"
+                    echo ">                                           <"
+                    echo "Your kernel is already backported, skipping"
+                    echo ">                                           <"
+                    echo ">>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<"
+                else
+                    if [[ ${{ env.FIRST_VERSION }} == 3 ]] && [[ ${{ env.SECOND_VERSION }} == 18 ]]; then
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_3.18.patch ./
+
+                        patch -p1 < backport_kernel_read_and_kernel_write_3.18.patch || true
+                    elif [[ ${{ env.FIRST_VERSION }} == 4 ]] && [[ ${{ env.SECOND_VERSION }} == 4 ]]; then
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_4.4.patch ./
+
+                        patch -p1 < backport_kernel_read_and_kernel_write_4.4.patch || true
+                    elif [[ ${{ env.FIRST_VERSION }} == 4 ]] && [[ ${{ env.SECOND_VERSION }} == 9 ]]; then
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_4.9.patch ./
+
+                        patch -p1 < backport_kernel_read_and_kernel_write_4.9.patch || true
+                    else
+                        echo "Could not support ARMV7A kernel(Kernel Version < 3.18)"
+                        false
+                    fi
+                    REJ_FOUND
+                fi
+
+                echo "executed backport patch (contain kernel_read and kernel_write patch) successfully."
+            else
+                cp /tmp/Patches/backport_patches.sh ./
+                bash backport_patches.sh
+
+                echo "executed backport patch successfully."
+            fi
+
           # Check syscall hook
           elif [[ ${{ env.HOOK_METHOD }} == "syscall" ]]; then
             cp /tmp/Patches/syscall_hook_patches.sh ./
